### ISSUE TITLE
var dict = { [object Object]: "George", [object Object]: 12 }; dict.fun example

### ISSUE THREAD

**Issue by NoobiCodi** [airportyh/fun-lang#1]
Hello !
I watched all videos about nearley they are just amazing !
I came here to see the fun-lang, but when i run the dictionnary example, there is a problem :
```javascript
var dict = { [object Object]: "George", [object Object]: 12 };
```
Here is the fun code : (file: mytest.fun)
```fun
proc main() [
    dict = { name: "George", age: 12 }
    dict["name"] = "Barnes"
    print(dict["name"])
]
```
Command i run
```bash
node scripts/run.js mytest.fun
```

**Comment by airportyh** [comment]
Thank you for the comment and the bug report! Fixed in master. It was due to the key of a dictionary entry being change (at some point) from a string to a token. Haven't covered tokens in the videos yet. Plan to.

**Comment by NoobiCodi** [comment]
👍 Thank you very much !
Your videos are awesome, I was searching simple and good tutorials for months when, one day, i found your channel: best channel for the subject
